server.port=8081
spring.application.name=HolidayTripAPI

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/holidaytripdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Gemini API Configuration (OpenAI Compatible)
# Lütfen buraya kendi Gemini API anahtarınızı (Google AI Studio'dan alıp) yapıştırın:
gemini.api.key=AQ.Ab8RN6IjrqefxaqWDayn2_jRx4JOnjJPZwgDga8uz_pbgt8_Uw
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/openai/chat/completions
gemini.api.model=gemini-3.5-flash-lite

#airlabs API anahtarı (uçuş bilgileri için)
airlabs.api.key=890cf774-0750-4c8e-a8f9-8194120cb2aa