server.port=8081
spring.application.name=HolidayTripAPI

# Gemini API Configuration (OpenAI Compatible)
# Lütfen buraya kendi Gemini API anahtarınızı (Google AI Studio'dan alıp) yapıştırın:
groq.api.key=AQ.Ab8RN6IjrqefxaqWDayn2_jRx4JOnjJPZwgDga8uz_pbgt8_Uw
groq.api.url=https://generativelanguage.googleapis.com/v1beta/openai/chat/completions
groq.api.model=gemini-3.5-flash-lite