server.port=8081
spring.application.name=HolidayTripAPI

# Groq API Configuration
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=openai/gpt-oss-20b
